# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via \{\{ site.title \}\}, \{\{ site.github_repo \}\}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via \{\{ site.myvariable \}\}.
title: "Stat 230a: Linear Models"
tagline: Course Overview
description: "Theory of least squares estimation, interval estimation, and tests under the general linear fixed effects model with normally distributed errors. Large sample theory for non-normal linear models. Two and higher way layouts, residual analysis. Effects of departures from the underlying assumptions. Robust alternatives to least squares. "
author: "SCF"
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://stat230a.berkeley.edu'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
logo: 'resources/logo.png'

ga_tracking: "G-XV9VYHN1MF"

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
